import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const directory = path.dirname(new URL(import.meta.url).pathname);
const catalog = JSON.parse(
  fs.readFileSync(path.join(directory, 'catalog.json'), 'utf8'),
);
const response = JSON.parse(
  fs.readFileSync(path.join(directory, 'response.example.json'), 'utf8'),
);
const schema = JSON.parse(
  fs.readFileSync(path.join(directory, 'response.schema.json'), 'utf8'),
);
const ownerAcknowledgement =
  schema.$defs.ownerAcceptance.properties.acknowledgement.anyOf[1].const;
const validator = path.join(directory, 'validate.mjs');
const cases = [
  [
    'missing answer',
    (catalog, response) => {
      response.answers.pop();
    },
  ],
  [
    'duplicate answer',
    (catalog, response) => {
      response.answers[1].decisionId = response.answers[0].decisionId;
    },
  ],
  [
    'unknown decision',
    (catalog, response) => {
      response.answers[0].decisionId = 'invented';
    },
  ],
  [
    'invalid answer value',
    (catalog, response) => {
      response.answers[0].value = 'invented';
    },
  ],
  [
    'catalog default not allowed',
    (catalog) => {
      catalog.decisions[0].defaultValue = 'invented';
    },
  ],
  [
    'catalog decision omitted',
    (catalog) => {
      catalog.decisions.pop();
    },
  ],
  [
    'catalog required-notes metadata omitted',
    (catalog) => {
      delete catalog.decisions[0].options.find(
        (option) => option.value === 'other',
      ).requiresNotes;
    },
  ],
  [
    'other answer without notes',
    (catalog, response) => {
      response.answers[0].value = 'other';
    },
  ],
  [
    'lower charging target without notes',
    (catalog, response) => {
      response.answers.find(
        (answer) => answer.decisionId === 'charging',
      ).value = 'lower-target';
    },
  ],
  [
    'draft acceptance leak',
    (catalog, response) => {
      response.ownerAcceptance.owner = 'Calum';
    },
  ],
  [
    'accepted missing acknowledgement',
    (catalog, response) => {
      response.responseStatus = 'OWNER_ACCEPTED';
      response.ownerAcceptance = {
        owner: 'Calum',
        date: '2026-09-01',
        evidence: 'issue comment',
        acknowledgement: null,
      };
    },
  ],
  [
    'accepted near-miss acknowledgement',
    (catalog, response) => {
      response.responseStatus = 'OWNER_ACCEPTED';
      response.ownerAcceptance = {
        owner: 'TEST OWNER',
        date: '2026-09-01',
        evidence: 'TEST EVIDENCE ONLY',
        acknowledgement: `${ownerAcknowledgement} `,
      };
    },
  ],
  [
    'null answers',
    (catalog, response) => {
      response.answers = null;
    },
  ],
  [
    'null catalog decisions',
    (catalog) => {
      catalog.decisions = null;
    },
  ],
  [
    'null catalog decision',
    (catalog) => {
      catalog.decisions[0] = null;
    },
  ],
];
for (const [name, mutate] of cases) {
  const caseName = String(name);
  const candidateCatalog = structuredClone(catalog);
  const candidateResponse = structuredClone(response);
  mutate(candidateCatalog, candidateResponse);
  const token = `${process.pid}-${caseName.replaceAll(' ', '-')}`;
  const catalogPath = path.join(
    os.tmpdir(),
    `tb4-kvm-product-catalog-${token}.json`,
  );
  const responsePath = path.join(
    os.tmpdir(),
    `tb4-kvm-product-response-${token}.json`,
  );
  fs.writeFileSync(catalogPath, JSON.stringify(candidateCatalog));
  fs.writeFileSync(responsePath, JSON.stringify(candidateResponse));
  const result = spawnSync(
    process.execPath,
    [validator, catalogPath, responsePath],
    { encoding: 'utf8' },
  );
  fs.rmSync(catalogPath, { force: true });
  fs.rmSync(responsePath, { force: true });
  if (result.status === 0) {
    console.error(`Adversarial mutant unexpectedly passed: ${caseName}`);
    process.exit(1);
  }
}

const acceptedResponse = structuredClone(response);
acceptedResponse.responseStatus = 'OWNER_ACCEPTED';
acceptedResponse.ownerAcceptance = {
  owner: 'TEST OWNER — NOT A REAL ACCEPTANCE',
  date: '2026-09-01',
  evidence: 'TEST EVIDENCE ONLY — generated by product-decision test.mjs',
  acknowledgement: ownerAcknowledgement,
};
const acceptedPath = path.join(
  os.tmpdir(),
  `tb4-kvm-product-response-${process.pid}-synthetic-owner-accepted.json`,
);
fs.writeFileSync(acceptedPath, JSON.stringify(acceptedResponse));
const acceptedResult = spawnSync(
  process.execPath,
  [validator, path.join(directory, 'catalog.json'), acceptedPath],
  { encoding: 'utf8' },
);
fs.rmSync(acceptedPath, { force: true });
if (acceptedResult.status !== 0) {
  console.error(
    'Synthetic OWNER_ACCEPTED response unexpectedly failed validation',
  );
  process.exit(1);
}
console.log(
  `Product decision tests passed: ${cases.length} rejected mutants plus synthetic OWNER_ACCEPTED response`,
);
